### ISSUE TITLE
pyretic

### ISSUE THREAD

**Issue by SIBTEALI12** [frenetic-lang/pyretic#70]
Hello, sir please guide me how to install pyretic in ubuntu 16.04. Also how to run pyretic because i am using  frenetic in oracle vbox but it cannot work proparly . I face fatal error and system halt issue ..please help me sir.

**Comment by joshreich** [comment]
As per the project homepage http://frenetic-lang.org/pyretic/ Pyretic is no longer being developed or supported. Many of Pyretic's features have been absorbed into Frenetic https://github.com/frenetic-lang/frenetic to which we direct interested developers.

**Comment by SIBTEALI12** [comment]
When i run frenetic get this error..

**Comment by SIBTEALI12** [comment]
Please send me an info
